---
- name: set up LAMP STACK
  hosts: localhost
  become: yes
  vars:
    http_port: 80
    domain: jenkins.letmovecloud.com
  tasks:
    - name: install firewalld by apt
      apt: name=firewalld state=present
    - name: 'Restarting firewalld'
      systemd:
        name: firewalld
        state: restarted
        enabled: true
        daemon_reload: true    
    - name: Install Firewalld
      firewalld:
        permanent: yes
        immediate: yes
        port: "{{item.port}}/{{item.proto}}"
        state: "{{item.state}}"
        zone: "{{item.zone}}"
      with_items:
        - { port: "3306", proto: "tcp", state: "enabled", zone: "public" } 
        - { port: "80", proto: "tcp", state: "enabled", zone: "public" }      
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
    - name: install madiadb server
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mariadb-server
    - name: configuration file my.cnf
      shell: cat /etc/mysql/my.cnf
    - name: checking for port allow 3306
      shell: cat /etc/mysql/mysql.cnf | grep 3306 | wc -l
      register: result
    - name: debug output
      debug: msg="{{result.stdout}}"
    - name: adding port = 3306 in /etc/mysql/my.cnf
      lineinfile: dest=/etc/mysql/my.cnf line="port = 3306"
      when: result.stdout == "0"
    - name: start mariadb
      service: name=mariadb state=started enabled=true
       
    - name: Install ansible python3 mysql dependency
      apt:
        name: python3-mysqldb
        state: latest
    - name: create mariadb db
      mysql_db:
        name: ecomdb
        state: present    
    - name: create mariadb user in ecomdb db
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: "*.*:ALL"
        state: present
    - name: run sql script
      mysql_query:
        login_db: ecomdb
        login_user: ecomuser
        login_password: ecompassword
        query:
          - USE ecomdb
          
          - CREATE TABLE products (id mediumint(8) unsigned NOT NULL
            auto_increment,Name varchar(255) default NULL,Price varchar(255)
            default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id))
            AUTO_INCREMENT=1
          - INSERT INTO products (Name,Price,ImageUrl) VALUES
            ("Laptop","101","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone
            Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png")
        single_transaction: true
    
    - name: install apache2 git  php php-mysql
      apt: name="{{ item }}" state=present update_cache=yes
      with_items:
        - php
        - apache2
        - php-mysql
        - git

    - name: shell command
      shell: sudo sed -i 's/index.html/index.php/g' /etc/apache2/mods-enabled/dir.conf
    
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2
        
    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2
    - name: a2ensite {{ domain }}
      command: a2ensite /etc/apache2/sites-available/jenkins.letmovecloud.com.conf
      args:
        creates: /etc/apache2/sites-available/jenkins.letmovecloud.com.conf
      notify:
        - restart apache2
    - name: a2dissite {{ domain }}
      command: a2dissite /etc/apache2/sites-available/000-default.conf  
      args:
        creates: /etc/apache2/sites-available/000-default.conf
      notify:
        - restart apache2    
        
    - name: git url to /var/www/letmovecloud.com
      git:
        repo: https://github.com/samimcloud2020/ansible-lamp.git
        dest: /var/www/jenkins.letmovecloud.com/
        update: no 
   
    - name: curl localhost
      shell: curl http://localhost:80/              

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
