---
- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

  #Apache Configuration
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache
      
    #install firewalld  
    - name: install firewalld by apt
      apt: name=firewalld state=present
    - name: 'Restarting firewalld'
      systemd:
        name: firewalld
        state: restarted
        enabled: true
        daemon_reload: true    
        
    - name: Install Firewalld
      firewalld:
        permanent: yes
        immediate: yes
        port: "{{item.port}}/{{item.proto}}"
        state: "{{item.state}}"
        zone: "{{item.zone}}"
      with_items:
        - { port: "3306", proto: "tcp", state: "enabled", zone: "public" } 
        - { port: "80", proto: "tcp", state: "enabled", zone: "public" }
        
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
  
     
   
    
      

  # MySQL Configuration
    - name: install madiadb server
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mariadb-server
        
    - name: configuration file my.cnf
      shell: cat /etc/mysql/my.cnf
      
    - name: checking for port allow 3306
      shell: cat /etc/mysql/mysql.cnf | grep 3306 | wc -l
      register: result
      
    - name: debug output
      debug: msg="{{result.stdout}}"
      
    - name: adding port = 3306 in /etc/mysql/my.cnf
      lineinfile: dest=/etc/mysql/my.cnf line="port = 3306"
      when: result.stdout == "0"
      
    - name: start mariadb
      service: name=mariadb state=started enabled=true
       
    - name: Install ansible python3 mysql dependency
      apt:
        name: python3-mysqldb
        state: latest
        
    - name: Sets the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
        
    - name: create mariadb db
      mysql_db:
        name: database1
        state: present        
        
    - name: create mariadb user in ecomdb db
      mysql_user:
        name: root
        password: root123
        priv: "*.*:ALL"
        state: present
    - name: Removes the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
        
    - name: run sql script
      mysql_query:
        login_db: database1
        login_user: root
        login_password: root123
        query:
          - USE db1
          
          - CREATE TABLE products (id mediumint(8) unsigned NOT NULL
            auto_increment,Name varchar(255) default NULL,Price varchar(255)
            default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id))
            AUTO_INCREMENT=1
          - INSERT INTO products (Name,Price,ImageUrl) VALUES
            ("Laptop","101","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone
            Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png")
        single_transaction: true      

  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  # PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/{{ http_host }}/info.php"

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
